version: '3.6'
services:
  dynamic-dashboards-generator:
    build:
      context: ./src/
      dockerfile: kafka_consumer.dockerfile
    image: "${DOCKER_REGISTRY}ngpaas/dynamic-dashboards-generator:${IMAGE_TAG}"
    env_file: .env
  dynamic-dashboards-generator-redis-worker:
    build:
      context: ./src/
      dockerfile: redis_worker.dockerfile
    image: "${DOCKER_REGISTRY}ngpaas/dynamic-dashboards-generator-redis-worker:${IMAGE_TAG}"
    env_file: .env